name: EcoBosses
version: ${projectVersion}
main: com.willfp.ecobosses.EcoBossesPlugin
api-version: 1.16
authors: [Auxilor]
website: willfp.com
load: STARTUP
depend:
  - eco

commands:
  ebreload:
    description: Reloads config
    permission: ecobosses.reload
  ebdrop:
    description: Sends the held item to console to be added as a drop
    permission: ecobosses.ebdrop
  ebspawn:
    description: Spawns a boss
    permission: ecobosses.ebspawn

permissions:
  ecobosses.*:
    description: All ecobosses permissions
    default: op
    children:
      ecobosses.reload: true
      ecobosses.ebdrop: true
      ecobosses.ebspawn: true

  ecobosses.reload:
    description: Allows reloading the config
    default: op

  ecobosses.ebdrop:
    description: Allows the use of /ebdrop
    default: op

  ecobosses.ebspawn:
    description: Allows the use of /ebspawn
    default: op