name: EcoBosses
version: ${projectVersion}
main: com.willfp.ecobosses.EcoBossesPlugin
api-version: 1.16
authors: [Auxilor]
website: willfp.com
load: STARTUP
depend:
  - eco

commands:
  ecobosses:
    description: Base command
    permission: ecobosses.command.ecobosses

permissions:
  ecobosses.*:
    description: All ecobosses permissions
    default: op
    children:
      ecobosses.command.*: true
  ecobosses.command.*:
    description: All ecobosses commands
    default: op
    children:
      ecobosses.command.ecobosses: true
      ecobosses.command.reload: true
      ecobosses.command.spawn: true
      ecobosses.command.base64: true

  ecobosses.command.ecobosses:
    description: Allows the use of /ecobosses
    default: true

  ecobosses.command.base64:
    description: Allows the use of /ecobosses base64
    default: op

  ecobosses.command.spawn:
    description: Allows the use of /ecobosses spawn
    default: op

  ecobosses.command.killall:
    description: Allows the use of /ecobosses killall
    default: op

  ecobosses.command.reload:
    description: Allows the use of /ecobosses reload
    default: op