name: Illusioner
version: ${projectVersion}
main: com.willfp.illusioner.IllusionerPlugin
api-version: 1.15
authors: [Auxilor]
website: willfp.com
load: STARTUP

commands:
  ilreload:
    description: Reloads config
    permission: illusioner.reload
  ildrop:
    description: Adds the item in your hand as a drop
    permission: illusioner.drop

permissions:
  illusioner.*:
    description: All illusioner permissions
    default: op
    children:
      illusioner.reload: true
      illusioner.updateannounce: true

  illusioner.updateannounce:
    description: Informs admins of a new update
    default: op
  illusioner.reload:
    description: Allows reloading the config
    default: op